version: '2'

services:
  monitor-app:
    build: .
    environment:
      - TZ=Asia/Yekaterinburg
    container_name: monitor-app
    volumes:
      - .:/app
    ports:
      - 9091:8000
    command: "monitor.py"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - 3000:3000

  prometheus:
    image: prom/prometheus
    container_name: monitor-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
